# Generated by Django 4.1.7 on 2023-03-08 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0016_alter_message_image'),
        ('usersapp', '0004_alter_users_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('verb', models.CharField(blank=True, default='verb --', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='desc --', null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('reception_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieption_notify', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_notify', to='roomsapp.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notify', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'الاشعارات',
                'ordering': ['-id'],
            },
        ),
    ]
