# Generated by Django 4.1.7 on 2023-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='verb',
        ),
        migrations.AddField(
            model_name='notification',
            name='device_id',
            field=models.CharField(blank=True, default='deviice_id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='title --', max_length=100, null=True),
        ),
    ]
