# Generated by Django 4.1.7 on 2023-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0006_rename_description_notification_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
