# Generated by Django 4.1.7 on 2023-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_alter_notification_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='device_id',
            new_name='token',
        ),
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='توكن'),
        ),
    ]
