# Generated by Django 4.1.7 on 2023-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_rename_device_id_notification_token_users_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
