# Generated by Django 4.1.7 on 2023-03-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0009_alter_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='الرسالة')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='توكن')),
                ('image', models.ImageField(null=True, upload_to='message_images', verbose_name='الصورة')),
                ('sendtime', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأنشاء')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_rec', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name_plural': 'التعليقات ',
                'ordering': ('-id',),
            },
        ),
    ]
