# Generated by Django 4.1.7 on 2023-03-14 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0010_users_stars_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
    ]
