# Generated by Django 4.1.7 on 2023-03-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0011_bans_addtime_alter_bans_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='addtime',
            new_name='sendtime',
        ),
    ]
