# Generated by Django 4.1.7 on 2023-03-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomsapp', '0012_rename_addtime_message_sendtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('id',), 'verbose_name_plural': 'الغرف'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AlterField(
            model_name='room',
            name='admins_password',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='rooms_images', verbose_name='الصورة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_owner', to=settings.AUTH_USER_MODEL, verbose_name='المؤسس'),
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='0', max_length=25, verbose_name='كلمة المرور'),
        ),
    ]
