# Generated by Django 4.1.7 on 2023-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0013_alter_room_options_remove_room_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='media/message_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='media/rooms_images', verbose_name='الصورة'),
        ),
    ]
