# Generated by Django 4.1.7 on 2023-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0014_alter_message_image_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='message_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='rooms_images', verbose_name='الصورة'),
        ),
    ]
