# Generated by Django 4.1.7 on 2023-03-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsapp', '0015_alter_message_image_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='message_images', verbose_name='الصورة'),
        ),
    ]
